# Databricks notebook source
# ruff: noqa: F821, E501, S608
"""Manual, bounded embedding generation and governed semantic-tool views. No schedules."""

import hashlib
import json
import math
import time
from datetime import UTC, datetime
from pathlib import Path

from databricks.sdk import WorkspaceClient
from pyspark.sql import functions as F

started = time.monotonic()
CATALOG = "intellify_databricks_demo"
MODEL = "system.ai.gte_large_en_v1_5"
ENDPOINT = "databricks-gte-large-en"
DOCUMENT_VERSION = "retail_product_document_v1"
TABLE = f"{CATALOG}.features.product_embeddings"
VOLUME = f"/Volumes/{CATALOG}/serving/semantic_assets"
assert spark.sql("SELECT current_user()").first()[0]
client = WorkspaceClient()
assert client.config.host.rstrip('/') == "https://adb-7405618180989330.10.azuredatabricks.net"
endpoint = client.serving_endpoints.get(ENDPOINT)
assert endpoint.config.served_entities[0].foundation_model.name == MODEL

views = {
    "tool_products": f"""SELECT product_id, product_name, category_id, category_name,
        brand_name, base_price, currency_code, available_qty,
        coalesce(active_discount_pct, 0.0) AS active_discount_pct,
        inventory_snapshot_at FROM {CATALOG}.gold.eligible_product_catalog""",
    "tool_customers": f"""SELECT customer_id, customer_segment, loyalty_tier,
        preferred_channel, region_id, behavior_as_of, purchase_count, browse_count
        FROM {CATALOG}.gold.customer_360 WHERE customer_status = 'Active'""",
    "tool_opportunities": f"""SELECT r.customer_id, r.product_id,
        'ACTIVE_PROMOTION' AS opportunity_type, p.active_discount_pct AS discount_pct
        FROM {CATALOG}.serving.customer_recommendations r
        JOIN {CATALOG}.gold.eligible_product_catalog p USING (product_id)
        WHERE p.active_discount_pct > 0 AND r.registered_model_version = '3'""",
    "tool_quality": f"""SELECT '3' AS model_version,
        count(DISTINCT customer_id) AS batch_customers, count(*) AS batch_rows,
        'SYNTHETIC_POC_ONLY' AS scope
        FROM {CATALOG}.serving.customer_recommendations WHERE registered_model_version = '3'""",
}
for name, select in views.items():
    spark.sql(f"CREATE OR REPLACE VIEW {CATALOG}.serving.{name} AS {select}")
    spark.sql(f"ALTER VIEW {CATALOG}.serving.{name} OWNER TO `retail_hp_admins`")
    spark.sql(f"GRANT SELECT ON TABLE {CATALOG}.serving.{name} TO `retail_hp_app_runtime`")

spark.sql(f"""CREATE TABLE IF NOT EXISTS {TABLE} (
    product_id STRING NOT NULL, document STRING NOT NULL, document_sha256 STRING NOT NULL,
    model_version STRING NOT NULL, document_version STRING NOT NULL,
    embedding ARRAY<DOUBLE> NOT NULL, generated_at TIMESTAMP NOT NULL
) USING DELTA TBLPROPERTIES ('delta.appendOnly'='true',
    'retail_hp.contract_version'='retail_hp_embeddings_v1')""")
spark.sql(f"ALTER TABLE {TABLE} OWNER TO `retail_hp_admins`")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {CATALOG}.serving.semantic_assets")
spark.sql(f"ALTER VOLUME {CATALOG}.serving.semantic_assets OWNER TO `retail_hp_admins`")
spark.sql(f"GRANT READ_VOLUME ON VOLUME {CATALOG}.serving.semantic_assets TO `retail_hp_app_runtime`")

products = spark.table(f"{CATALOG}.gold.eligible_product_catalog").select(
    "product_id", "product_name", "category_name", "department_name", "brand_name", "season", "color", "size"
).orderBy("product_id").limit(3001).collect()
assert 0 < len(products) <= 3000
assert len({p.product_id for p in products}) == len(products)
existing_rows = spark.table(TABLE).where(
    (F.col("model_version") == MODEL) & (F.col("document_version") == DOCUMENT_VERSION)
).select("product_id", "document_sha256").limit(9001).collect()
assert len(existing_rows) <= 9000
existing = {(r.product_id, r.document_sha256): r.asDict() for r in existing_rows}
assert len(existing) == len(existing_rows)
documents = []
for product in products:
    document = " | ".join(str(product[column] or "") for column in
        ("product_name", "category_name", "department_name", "brand_name", "season", "color", "size"))
    assert 0 < len(document) <= 512
    documents.append((product.product_id, document, hashlib.sha256(document.encode()).hexdigest()))
snapshot_version = hashlib.sha256(json.dumps(
    {"model": MODEL, "document_version": DOCUMENT_VERSION,
     "documents": [(pid, digest) for pid, _, digest in documents]}, sort_keys=True
).encode()).hexdigest()
pending = [row for row in documents if (row[0], row[2]) not in existing]
tokens = 0  # Embeddings are generated by phase8_embed.py while Spark is off.
new_rows = []
if pending:
    prepared_path = Path(VOLUME) / f"precomputed_{snapshot_version}.json"
    assert prepared_path.exists(), "Run checkpointed phase8_embed.py before starting this job"
    assert prepared_path.stat().st_size < 80_000_000
    prepared = json.loads(prepared_path.read_text())
    assert prepared["model"] == MODEL and prepared["snapshot_version"] == snapshot_version
    imported = {(r["product_id"], r["document_sha256"]): r for r in prepared["rows"]}
    assert len(imported) == len(prepared["rows"]) == len(documents)
    for pid, document, digest in pending:
        row = imported[(pid, digest)]
        assert row["document"] == document and row["model_version"] == MODEL
        assert row["document_version"] == DOCUMENT_VERSION
        vector = row["embedding"]
        assert len(vector) == 1024 and all(math.isfinite(x) for x in vector)
        assert abs(math.sqrt(math.fsum(x * x for x in vector)) - 1) < 0.001
        row["generated_at"] = datetime.fromisoformat(row["generated_at"]).astimezone(UTC).replace(tzinfo=None)
        new_rows.append(row)
        existing[(pid, digest)] = row
if new_rows:
    schema = spark.table(TABLE).schema
    spark.createDataFrame(new_rows, schema=schema).createOrReplaceTempView("phase8_new_embeddings")
    spark.sql(f"""MERGE INTO {TABLE} t USING phase8_new_embeddings s
        ON t.product_id=s.product_id AND t.document_sha256=s.document_sha256
        AND t.model_version=s.model_version AND t.document_version=s.document_version
        WHEN NOT MATCHED THEN INSERT *""")
snapshot_path = Path(VOLUME) / f"{snapshot_version}.json"
if not snapshot_path.exists():
    vectors = spark.table(TABLE).where(
        (F.col("model_version") == MODEL) & (F.col("document_version") == DOCUMENT_VERSION)
    ).limit(9001).collect()
    lookup = {(r.product_id, r.document_sha256): r.embedding for r in vectors}
    snapshot = {"model": MODEL, "document_version": DOCUMENT_VERSION,
                "snapshot_version": snapshot_version, "generated_at": datetime.now(UTC).isoformat(),
                "rows": [{"product_id": pid, "embedding": lookup[(pid, digest)]}
                         for pid, _, digest in documents]}
    with snapshot_path.open("x", encoding="utf-8") as handle:
        json.dump(snapshot, handle, separators=(",", ":"))
stored = json.loads(snapshot_path.read_text())
assert stored["snapshot_version"] == snapshot_version and len(stored["rows"]) == len(documents)
stored_rows = spark.table(TABLE).where(
    (F.col("model_version") == MODEL) & (F.col("document_version") == DOCUMENT_VERSION)
).select("product_id", "document_sha256").limit(9001).collect()
stored_keys = {(r.product_id, r.document_sha256) for r in stored_rows}
assert all((pid, digest) in stored_keys for pid, _, digest in documents)
dbutils.notebook.exit(json.dumps({
    "status": "PASS", "eligible_products": len(documents), "embedded_new": len(new_rows),
    "reused": len(documents) - len(new_rows), "embedding_tokens": tokens,
    "snapshot_version": snapshot_version, "snapshot_path": str(snapshot_path),
    "model": MODEL, "views": sorted(views), "schedule": None,
    "elapsed_seconds": round(time.monotonic() - started, 2),
}))
